// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyoynevyfalwiziwjdmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5b3luZXZ5ZmFsd2l6aXdqZG1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1NDg0ODEsImV4cCI6MjA1NDEyNDQ4MX0.ZyNd13B2pSLOsfV79xGasKHPTHPnZWjnBeSIAix4z9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);